services:
  duckdns:
    image: lscr.io/linuxserver/duckdns
    env_file:
      - ../.env
    user: "${UID:-0}:${GID:-0}"
    environment:
      - TZ=${TZ}
      - FILE__SUBDOMAINS=/run/secrets/duckdns_subdomains
      - FILE__TOKEN=/run/secrets/duckdns_token
      - LOG_FILE=false
    secrets:
      - duckdns_subdomains
      - duckdns_token
    volumes:
      - config:/config
    networks:
      - local
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

secrets:
  duckdns_subdomains:
    external: true
  duckdns_token:
    external: true

volumes:
  config:

networks:
  local:
    driver: overlay
    attachable: true
