services:
  duckdns:
    image: lscr.io/linuxserver/duckdns
    user: "${DOCKER_PUID:-0}:${DOCKER_PGID:-0}"
    environment:
      - SUBDOMAINS=${WIREGUARD_DOMAIN_NAME:?error}
      - FILE__TOKEN=/run/secrets/duckdns_token
      - LOG_FILE=false
    secrets:
      - duckdns_token
    networks:
      - network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

secrets:
  duckdns_token:
    external: true

networks:
  network:
    name: ${DOCKER_NETWORK:?error}
    external: true
