services:
  duplicati:
    image: duplicati/duplicati:latest
    env_file:
      - ../.env
    user: "${UID:-0}:${GID:-0}"
    environment:
      - SETTINGS_ENCRYPTION_KEY="<real encryption key>"
      - DUPLICATI__WEBSERVICE_PASSWORD="<ui password>"
    volumes:
      - data:/data
    networks:
      - local
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  data:

networks:
  local:
    driver: overlay
    attachable: true
