services:
  duplicati:
    image: duplicati/duplicati:latest
    hostname: "{{.Node.Hostname}}"
    user: "${DOCKER_PUID:-0}:${DOCKER_PGID:-0}"
    environment:
      - SETTINGS_ENCRYPTION_KEY=${SETTINGS_ENCRYPTION_KEY}
      - DUPLICATI__WEBSERVICE_PASSWORD=${DUPLICATI__WEBSERVICE_PASSWORD:-admin}
    volumes:
      - duplicati_data:/data
    networks:
      - network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.duplicati.rule=Host(`duplicati.${TRAEFIK_DOMAIN_NAME:?error}`)"
        - "traefik.http.services.duplicati.loadbalancer.server.port=8200"

volumes:
  duplicati_data:
    name: duplicati_data

networks:
  network:
    name: ${DOCKER_NETWORK:?error}
    external: true
