services:
  duplicati:
    image: duplicati/duplicati:latest
    user: "${UID:-0}:${GID:-0}"
    environment:
      - SETTINGS_ENCRYPTION_KEY=${SETTINGS_ENCRYPTION_KEY}
      - DUPLICATI__WEBSERVICE_PASSWORD=${DUPLICATI__WEBSERVICE_PASSWORD:-admin}
    volumes:
      - data:/data
    networks:
      - local
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  data:

networks:
  local:
    driver: overlay
    attachable: true
