services:
  vaultwarden:
    image: vaultwarden/server:latest
    environment:
      - DOMAIN=vaultwarden.${TRAEFIK_DOMAIN_NAME:?error}
      - SIGNUPS_ALLOWED=true
    volumes:
      - data:/data/
    networks:
      - network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.${TRAEFIK_DOMAIN_NAME:?error}`)"
        - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"

volumes:
  data:
    name: vaultwarden_data

networks:
  network:
    name: ${DOCKER_NETWORK:?error}
    external: true
