services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    user: "${UID:-0}:${GID:-0}"
    privileged: true
    environment:
      - TZ=${TZ:-Europe/Paris}
    devices:
      - ${SKYCONNECT_DEV:-/dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_0e9226d6be96ed11b33dc698a7669f5d-if00-port0}:/dev/ttyUSB0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - config:/config
    networks:
      - local
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

volumes:
  config:

networks:
  local:
    driver: overlay
    attachable: true
