services:
  pihole:
    image: pihole/pihole:latest
    user: "${DOCKER_PUID:-0}:${DOCKER_PGID:-0}"
    secrets:
      - password
    environment:
      - TZ=${TZ:?error}
      - WEBPASSWORD_FILE=/run/secrets/password
    volumes:
      - config:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    ports:
      - "53:53"
    networks:
      - ${DOCKER_NETWORK:?error}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pihole.rule=Host(`pihole.${TRAEFIK_DOMAIN_NAME:?error}`)"
        - "traefik.http.routers.pihole.entrypoints=websecure"
        - "traefik.http.routers.pihole.tls.certresolver=dnschallenge"
        - "traefik.http.services.pihole.loadbalancer.server.port=80"

secrets:
  password:
    external: true

volumes:
  config:
  dnsmasq:

networks:
  ${DOCKER_NETWORK:?error}:
    external: true
