services:
  pihole:
    image: pihole/pihole:latest
    user: "${UID}:${GID}"
    environment:
      - TZ=${TZ} # cat /etc/timezone
      - WEBPASSWORD=${WEBPASSWORD}
    volumes:
      - config:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    ports:
      - 53:53
    networks:
      - local
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

volumes:
  config:
  dnsmasq:

networks:
  local:
