services:
  grafana:
    image: grafana/grafana:latest
    env_file:
      - ../.env
    user: "${UID:-0}:${GID:-0}"
    environment:
      - GF_SECURITY_ADMIN_USER=${USERNAME:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${PASSWORD:-admin}
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_INSTALL_PLUGINS=
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - local
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
  influxdb:
    image: influxdb:1.8
    env_file:
      - ../.env
    user: "${UID:-0}:${GID:-0}"
    environment:
      - INFLUXDB_DB=influxdb
      - INFLUXDB_ADMIN_USER=${USERNAME:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${PASSWORD:-admin}
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - local
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
  telegraf:
    image: telegraf:latest
    env_file:
      - ../.env
    user: "${UID:-0}:${GID:-0}"
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
    volumes:
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - telegraf_config:/etc/telegraf
    networks:
      - local
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

volumes:
  grafana_data:
  influxdb_data:
  telegraf_config:

networks:
  local:
    driver: overlay
    attachable: true
