services:
  node_red:
    image: eclipse-mosquitto:latest
    user: "${DOCKER_PUID:-0}:${DOCKER_PGID:-0}"
    environment:
      - TZ=${DOCKER_TZ:?error}
    volumes:
      - data:/data
    networks:
      - network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nodered.rule=Host(`mosquitto.${TRAEFIK_DOMAIN_NAME:?error}`)"
        - "traefik.http.services.nodered.loadbalancer.server.port=1883"

volumes:
  data:
    name: node_red_data

networks:
  network:
    name: ${DOCKER_NETWORK:?error}
    external: true
