services:
  traefik:
    image: "traefik:3.2"
    user: "${DOCKER_PUID:-0}:${DOCKER_PGID:-0}"
    command:
      - "--global.checknewversion=true"
      - "--global.sendanonymoususage=false"
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--log=true"
      - "--log.level=DEBUG"
      - "--metrics.prometheus=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--providers.swarm.network=${DOCKER_NETWORK:?error}"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.asdefault=true"
      - "--entrypoints.websecure.http.tls.certresolver=letsencrypt"
      - "--entrypoints.websecure.http.tls.domains[0].main=${TRAEFIK_DOMAIN_NAME:?error}"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.${TRAEFIK_DOMAIN_NAME:?error}"
      # - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.email=${DUCKDNS_EMAIL:?error}"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=duckdns"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    environment:
      - DUCKDNS_TOKEN_FILE=/run/secrets/duckdns_token
      - DUCKDNS_PROPAGATION_TIMEOUT=120
      - DUCKDNS_POLLING_INTERVAL=30
      - DUCKDNS_TTL=200
    secrets:
      - duckdns_token
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_certs:/letsencrypt
    networks:
      - network
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.${TRAEFIK_DOMAIN_NAME:?error}`)"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users=${BASICAUTH_USERNAME:?error}:${BASICAUTH_PASSWORD_HASH:?error}"
        - "traefik.http.services.traefik.loadbalancer.server.port=9999"

secrets:
  duckdns_token:
    external: true

volumes:
  traefik_certs:
    name: traefik_certs

networks:
  network:
    name: ${DOCKER_NETWORK:?error}
    external: true
