services:
  traefik:
    image: "traefik:v2.10"
    user: "${DOCKER_PUID:-0}:${DOCKER_PGID:-0}"
    command:
      - "--log.level=DEBUG" # to remove
      - "--global.checknewversion=true"
      - "--global.sendanonymoususage=false"
      - "--api=true"
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--metrics.prometheus"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.network=${DOCKER_NETWORK:?error}"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.certresolver=letsencrypt"
      - "--entrypoints.websecure.http.tls.domains[0].main=${TRAEFIK_DOMAIN_NAME:?error}"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.${TRAEFIK_DOMAIN_NAME:?error}"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=duckdns"
      - "--certificatesresolvers.letsencrypt.acme.email=${DUCKDNS_EMAIL:?error}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DUCKDNS_TOKEN_FILE=/run/secrets/duckdns_token
      - DUCKDNS_PROPAGATION_TIMEOUT=120
      - DUCKDNS_POLLING_INTERVAL=30
      - DUCKDNS_TTL=200
    secrets:
      - duckdns_token
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_data:/letsencrypt
    networks:
      - network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        # - "traefik.http.routers.traefik.rule=Host(`traefik.${TRAEFIK_DOMAIN_NAME:?error}`) && ((PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
        # - "traefik.http.routers.traefik.service=dashboard@internal"
        # - "traefik.http.routers.traefik.middlewares=auth"
        - "traefik.http.routers.traefik.rule=Host(`traefik.${TRAEFIK_DOMAIN_NAME:?error}`)"
        - "traefik.http.routers.traefik.service=dashboard@internal"
        - "traefik.http.routers.traefik.middlewares=auth"
        - "traefik.http.routers.traefik_api.rule=Host(`traefik_api.${TRAEFIK_DOMAIN_NAME:?error}`)"
        - "traefik.http.routers.traefik_api.service=api@internal"
        - "traefik.http.routers.traefik_api.middlewares=auth"
        - "traefik.http.routers.traefik_metrics.rule=Host(`traefik_metrics.${TRAEFIK_DOMAIN_NAME:?error}`)"
        - "traefik.http.routers.traefik_metrics.service=prometheus@internal"
        - "traefik.http.routers.traefik_metrics.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users=${BASICAUTH_USERNAME:?error}:${BASICAUTH_PASSWORD_HASH:?error}"

secrets:
  duckdns_token:
    external: true

volumes:
  traefik_data:

networks:
  network:
    name: ${DOCKER_NETWORK:?error}
    external: true
