services:
  pgadmin:
    image: dpage/pgadmin4:latest
    user: "${DOCKER_PUID:-0}:${DOCKER_PGID:-0}"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:?error}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/password
    secrets:
      - password
    volumes:
      - data:/var/lib/pgadmin
    networks:
      - network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.${TRAEFIK_DOMAIN_NAME:?error}`)"
        - "traefik.http.services.pgadmin.loadbalancer.server.port=80"

secrets:
  password:
    external: true

volumes:
  data:
    name: pgadmin_data

networks:
  network:
    name: ${DOCKER_NETWORK:?error}
    external: true
