services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    user: "${DOCKER_PUID:-0}:${DOCKER_PGID:-0}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - homepage_config:/app/config
    networks:
      - network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.homepage.rule=Host(`${TRAEFIK_DOMAIN_NAME:?error}`) || Host(`homepage.${TRAEFIK_DOMAIN_NAME:?error}`)"
        - "traefik.http.services.homepage.loadbalancer.server.port=3000"

volumes:
  homepage_config:
    name: homepage_config

networks:
  network:
    name: ${DOCKER_NETWORK:?error}
    external: true
