services:
  nodered:
    image: nodered/node-red:latest
    user: "${UID:-0}:${GID:-0}"
    environment:
      - TZ=${TZ:-Europe/Paris}
    volumes:
      - data:/data
    networks:
      - local
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  data:

networks:
  local:
    driver: overlay
    attachable: true
