services:
  agent:
    image: portainer/agent:latest
    user: "${DOCKER_PUID:-0}:${DOCKER_PGID:-0}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
      restart_policy:
        condition: on-failure

  portainer:
    image: portainer/portainer-ce:latest
    user: "${DOCKER_PUID:-0}:${DOCKER_PGID:-0}"
    command: "-H tcp://tasks.agent:9001 --tlsskipverify"
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    volumes:
      - portainer_data:/data
    networks:
      - network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=Host(`portainer.${TRAEFIK_DOMAIN_NAME:?error}`)"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"

volumes:
  portainer_data:
    name: portainer_data

networks:
  network:
    name: ${DOCKER_NETWORK:?error}
    external: true
