services:
  dashy:
    image: lissy93/dashy:latest
    env_file:
      - ../.env
    user: "${UID:-0}:${GID:-0}"
    environment:
      - NODE_ENV=production
    volumes:
      - config:/app/public
    networks:
      - local
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  config:

networks:
  local:
    driver: overlay
    attachable: true
