services:
  influxdb:
    image: influxdb:1.8
    user: "${DOCKER_PUID:-0}:${DOCKER_PGID:-0}"
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB:-influxdb}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-admin}
    volumes:
      - data:/var/lib/influxdb
    networks:
      - network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  data:
    name: influxdb_data

networks:
  network:
    name: ${DOCKER_NETWORK:?error}
    external: true
