services:
  wireguard:
    image: ghcr.io/wg-easy/wg-easy:latest
    user: "${DOCKER_PUID:-0}:${DOCKER_PGID:-0}"
    environment:
      - WG_HOST=${WIREGUARD_DOMAIN_NAME:?error}
      # docker run --rm -it ghcr.io/wg-easy/wg-easy wgpw 'admin'
      # - PASSWORD_HASH=${PASSWORD_HASH:?error}
      - ENABLE_PROMETHEUS_METRICS=true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - "51820:51820/udp"
    volumes:
      - data:/etc/wireguard
    networks:
      - ${DOCKER_NETWORK:?error}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wireguard.rule=Host(`wireguard.${TRAEFIK_DOMAIN_NAME:?error}`)"
        - "traefik.http.routers.wireguard.entrypoints=websecure"
        - "traefik.http.routers.wireguard.tls.certresolver=dnschallenge"
        - "traefik.http.services.wireguard.loadbalancer.server.port=51821"

volumes:
  data:

networks:
  ${DOCKER_NETWORK:?error}:
    external: true
