services:
  wireguard:
    image: ghcr.io/wg-easy/wg-easy:latest
    user: "${DOCKER_PUID:-0}:${DOCKER_PGID:-0}"
    environment:
      - WG_HOST=${WIREGUARD_DOMAIN_NAME:?error}
      # - PASSWORD_HASH=${WIREGUARD_PASSWORD_HASH:?error}
      - ENABLE_PROMETHEUS_METRICS=true
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=1
      - UI_ENABLE_SORT_CLIENTS=true
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - wireguard_config:/etc/wireguard
    ports:
      - "51820:51820/udp"
    networks:
      - network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wireguard.rule=Host(`wireguard.${TRAEFIK_DOMAIN_NAME:?error}`)"
        - "traefik.http.services.wireguard.loadbalancer.server.port=51821"

volumes:
  wireguard_config:
    name: wireguard_config

networks:
  network:
    name: ${DOCKER_NETWORK:?error}
    external: true
