services:
  cache:
    image: redis:alpine
    user: "${DOCKER_PUID:-0}:${DOCKER_PGID:-0}"
    command:
      - "--save 60 1"
      - "--loglevel warning"
    volumes:
      - cache:/data
    networks:
      - network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  cache:
    name: redis_cache

networks:
  network:
    name: ${DOCKER_NETWORK:?error}
    external: true
